Q1) Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:

def divide_by_zero():
  try:
    a = 5/0
  except ZeroDivisionError as e:
    print(e ,"error")

divide_by_zero()

division by zero error


Q2) Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [2]:
subjects = ["Americans" , "Indians"]
verbs = ["play" , "watch"]
objects = ["Basketball" , "Cricket"]

for i in range(len(subjects)):
  for j in range(len(verbs)):
    for k in range(len(objects)):
      print(subjects[i] , verbs[j] , objects[k])

Americans play Basketball
Americans play Cricket
Americans watch Basketball
Americans watch Cricket
Indians play Basketball
Indians play Cricket
Indians watch Basketball
Indians watch Cricket


Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [3]:
import numpy as np
list = [1,2,3,5]
n = 4
p=0
array = np.array([ [ list[i]**(n-(j+1))  for j in range(0,n) if j<4] for i in range(len(list)) ])
print(array)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
